version: '3.4'

services:
  count4u.service.webapi.authentication:
    image: ${DOCKER_REGISTRY-}count4uservicewebapiauthentication
    build:
      context: .
      dockerfile: src\Count4U.Service.WebAPI.Authentication\Dockerfile
